# Autogenerated wrapper script for fast_float_jll for any
export fast_float_h

JLLWrappers.@generate_wrapper_header("fast_float")
JLLWrappers.@declare_file_product(fast_float_h)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        fast_float_h,
        "include/fast_float/fast_float.h",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
